# From here: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-ยง-ci.html
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.7"
  - "3.8"
install:
  # Install phase of our CI pipeline
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -y -q --name mini-project --file requirements.txt
  - conda activate  mini-project

script:
  # Run phase of our CI pipeline
  - pytest --cov=./ -v tests.py #runs test
  - coveralls #uploads coverage report to coveralls.io